# Generated by Django 6.0.1 on 2026-03-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='temporal', max_length=100),
            preserve_default=False,
        ),
    ]
