# Generated by Django 6.0.5 on 2026-05-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=100)),
                ('descripcion_plato', models.TextField()),
                ('precio_plato', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('asistio', 'ASISTIO'), ('cancelada', 'CANCELADA')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=1)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.plato')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_pedidos', to='reservas.reserva')),
            ],
        ),
    ]
